### ISSUE TITLE
Internal Dep of webEngage Android SDK in `Android-Seg` module uses `+` in version spec, leading to build FAILURES

### ISSUE THREAD

**Issue by s-ayush2903** [WebEngage/segment-integration-android#1]
The `+` being used in the dependency present in `android-segment` module leads to the usage of latest version of work-manager(2.0.7 as of now), which REQUIRES **minSDK to be 31** which fails the build pointlessly in the applications which do not have minSDK to be 31.

https://github.com/WebEngage/segment-integration-android/blob/e65320ccb0f9cdb60dfb44757d43560bbc536227/android-segment/build.gradle#L20

|Build Failure|Dep tree telling usage of `+` in version spec|
|---|--|
|![image](https://user-images.githubusercontent.com/56556919/138836905-478a4fc2-2cb1-4def-8059-c14c120d109d.png)|![image](https://user-images.githubusercontent.com/56556919/138837224-bc783400-64ca-4dd9-b15c-deeb7598b25a.png)|

Please point to the version of `com.webengage:android-sdk`, which does _not_ use [`v2.7.0`](https://developer.android.com/jetpack/androidx/releases/work#2.7.0) of work manager

**Comment by s-ayush2903** [comment]
@shahrukhimam fyi

**Comment by vitalii-movchan-mesh** [comment]
Hi dev team,

Additionally app start crashing, here is a short log:

![image](https://user-images.githubusercontent.com/64690512/138888114-aceb7dbe-7f49-45e6-9bad-95a69ddc9043.png)

I have solved this issue by force downgrade of transitive dependency, cc: @s-ayush2903 
```
app/buid.gradle

configurations.all {
    resolutionStrategy {
        force 'com.webengage:android-sdk:3.18.6'
    }
}

**Comment by SarthakWebEngage** [comment]
Hello @s-ayush2903,
We apologise for the inconvenience; please follow the steps below to make it work for targetSDK 30.
As WebEngage SDK 3.18.7 supports android 12, we highly recommend you to use 3.18.6.

Kindly paste the following code inside your app level gradle [app/buid.gradle]
```
configurations.all {
    resolutionStrategy {
        force 'com.webengage:android-sdk:3.18.6'
    }
}
```
You can also exclude the module dependency by doing the below:

```
 implementation ('com.webengage:android-segment:2.+') {
        exclude group: "androidx.work"
    }
```
We are already working to release the fix in our plugin.

**Comment by SarthakWebEngage** [comment]
Hi @VitaliiFront ,

Please accept our apologies for the inconvenience; could you please assist us with the use-case so that we can investigate your crash issue?

**Comment by DakshJainLeap** [comment]
Hi @SarthakWebEngage  I am getting same crash, and I am not able to resolve this with the solution provided by @VitaliiFront 
It happens when I include android-segment dependency (implementation 'com.webengage:android-segment:2.+')
Here is my crash logs

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.knudge.ielts/com.knudge.me.activity.MainFragmentActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by SarthakWebEngage** [comment]
Hi @DakshJainLeap 
Please accept our apologies for the inconvenience, here we are unable to replicate the issue, can you send us more details around the integration and which Android API version you are using and app's buid.gradle file on sarthak.sharma@webklipper.com ?

Also, kindly check whether you have added the above lines in the Android section of your app's build.gradle 
It would really help us to resolve this faster.
Thank you.

**Comment by SarthakWebEngage** [comment]
@s-ayush2903 Kindly upgrade the plugin to 2.0.7.
